export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_MODAL_TYPE = 'SET_MODAL_TYPE';

export const FILTER_CONTACTS = 'FILTER_CONTACTS';

export const ADD_CONTACT = 'ADD_CONTACT';

export const SAVE_EDITED_CONTACT = 'SAVE_EDITED_CONTACT';

export const DELETE_CONTACT = 'DELETE_CONTACT';

export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT';


