export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const FILTER_CONTACTS = 'FILTER_CONTACTS';

export const ADD_CONTACT = 'ADD_CONTACT';

export const SAVE_EDITED_CONTACT = 'SAVE_EDITED_CONTACT';

export const DELETE_CONTACT = 'ADD_CONTACT';


